package br.com.br.gatend.GestaoCliente.v1.model.eo;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 14:36:49 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U707GcCategAnexoVEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CategoryId,
        FunctionName,
        FunctionType,
        Categoria;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int FUNCTIONNAME = AttributesEnum.FunctionName.index();
    public static final int FUNCTIONTYPE = AttributesEnum.FunctionType.index();
    public static final int CATEGORIA = AttributesEnum.Categoria.index();

    /**
     * This is the default constructor (do not remove).
     */
    public U707GcCategAnexoVEOImpl() {
    }

    /**
     * @param categoryId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(oracle.jbo.domain.Number categoryId) {
        return new Key(new Object[] { categoryId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("br.com.br.gatend.GestaoCliente.v1.model.eo.U707GcCategAnexoVEO");
    }
}

