package br.com.br.gatend.GestaoCliente.v1.model.am.client;

import br.com.br.gatend.GestaoCliente.v1.model.am.common.AnexoAM;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 18 15:45:45 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnexoAMClient extends ApplicationModuleImpl implements AnexoAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AnexoAMClient() {
    }


    public String buscaDadosCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "buscaDadosCliente", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public Map pesquisarAnexoPorId(String id) {
        Object _ret = this.riInvokeExportedMethod(this, "pesquisarAnexoPorId", new String[] { "java.lang.String" }, new Object[] {
                                                  id });
        return (Map) _ret;
    }

    public void pesquisarAnexosPorCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "pesquisarAnexosPorCliente", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return;
    }

    public String removerAnexo(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "removerAnexo", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public String retornaNumeroSequecial(String codigoCliente) {
        Object _ret = this.riInvokeExportedMethod(this, "retornaNumeroSequecial", new String[] { "java.lang.String" }, new Object[] {
                                                  codigoCliente });
        return (String) _ret;
    }

    public String salvaAnexo(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "salvaAnexo", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }
}

