package br.com.br.gatend.GestaoCliente.v1.model.am.client;

import br.com.br.gatend.GestaoCliente.v1.model.am.common.CancelarClienteAM;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 24 09:56:56 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CancelarClienteAMClient extends ApplicationModuleImpl implements CancelarClienteAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CancelarClienteAMClient() {
    }


    public Map execProcCancelarCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "execProcCancelarCliente", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (Map) _ret;
    }

    public boolean getContratos(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "getContratos", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean getOportunidadeDRPS(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "getOportunidadeDRPS", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean getOportunidadeGNE(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "getOportunidadeGNE", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean getPrivilegioAcesso(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "getPrivilegioAcesso", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public String getUserId() {
        Object _ret = this.riInvokeExportedMethod(this, "getUserId", null, null);
        return (String) _ret;
    }

    public String localizaCnpjCompleto(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizaCnpjCompleto", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public String localizaCodEstrangeiroCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizaCodEstrangeiroCliente", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return (String) _ret;
    }

    public String localizaCpfCompleto(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizaCpfCompleto", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public String localizaPaisCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizaPaisCliente", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public Map localizarClientePeloCodigoR3(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizarClientePeloCodigoR3", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return (Map) _ret;
    }

    public boolean validaPrivilegioAcessoClientes(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "validaPrivilegioAcessoClientes", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return ((Boolean) _ret).booleanValue();
    }
}

