package br.com.br.gatend.GestaoCliente.v1.model.am.client;

import br.com.br.gatend.GestaoCliente.v1.model.am.common.ClientesAM;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 07 13:42:06 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClientesAMClient extends ApplicationModuleImpl implements ClientesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ClientesAMClient() {
    }


    public Map localizarClientePeloCodigoR3(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizarClientePeloCodigoR3", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return (Map) _ret;
    }


    public boolean localizarClientes(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizarClientes", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public String localizarPaisCliente(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "localizarPaisCliente", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return (String) _ret;
    }

    public boolean validaPrivilegioAcessoClientes(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "validaPrivilegioAcessoClientes", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return ((Boolean) _ret).booleanValue();
    }
}

