package br.com.br.gatend.GestaoCliente.v1.model.am.client;

import br.com.br.gatend.GestaoCliente.v1.model.am.common.LatitudeLongitudeAM;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 13 13:46:08 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LatitudeLongitudeAMClient extends ApplicationModuleImpl implements LatitudeLongitudeAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LatitudeLongitudeAMClient() {
    }


    public boolean confirmarLatitudeLongitude() {
        Object _ret = this.riInvokeExportedMethod(this, "confirmarLatitudeLongitude", null, null);
        return ((Boolean) _ret).booleanValue();
    }


    public void alteraValorSelecionadoPeloIndice(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "alteraValorSelecionadoPeloIndice", new String[] {
                                                  "java.util.Map" }, new Object[] { parametros });
        return;
    }

    public boolean confirmarLatitudeLongitude(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "confirmarLatitudeLongitude", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return ((Boolean) _ret).booleanValue();
    }

    public void consultarLatitudeLongitude(Map parametros) {
        Object _ret = this.riInvokeExportedMethod(this, "consultarLatitudeLongitude", new String[] { "java.util.Map" }, new Object[] {
                                                  parametros });
        return;
    }

    public void emptyTableLatLong() {
        Object _ret = this.riInvokeExportedMethod(this, "emptyTableLatLong", null, null);
        return;
    }
}

