package br.com.br.gatend.GestaoCliente.v1.model.vo.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 17:28:59 BRT 2014
// ---------------------------------------------------------------------
public interface ListaChecklistVORow extends Row {
    oracle.jbo.domain.Number getChecChvChecklist();

    void setChecChvChecklist(oracle.jbo.domain.Number value);

    String getLookupCode();

    String getChecIndVer();

    String getMeaning();

    String getLastUpdateBy();

    String getChecTxtJus();

    String getUserName();

    Date getLastUpdateDate();

    oracle.jbo.domain.Number getPartySiteId();

    Boolean getChecked();
}

