package br.com.br.gatend.GestaoCliente.v1.model.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 24 09:56:56 BRT 2014
// ---------------------------------------------------------------------
public interface CancelarClienteAM extends ApplicationModule {
    String localizaCnpjCompleto(Map parametros);

    Map localizarClientePeloCodigoR3(Map parametros);

    String localizaCodEstrangeiroCliente(Map parametros);

    String localizaPaisCliente(Map parametros);

    String localizaCpfCompleto(Map parametros);

    boolean getOportunidadeDRPS(Map parametros);

    boolean getOportunidadeGNE(Map parametros);

    boolean getContratos(Map parametros);

    Map execProcCancelarCliente(Map parametros);

    String getUserId();

    boolean validaPrivilegioAcessoClientes(Map parametros);

    boolean getPrivilegioAcesso(Map parametros);
}

