package br.com.br.gatend.GestaoCliente.v1.model.am.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 17:30:49 BRT 2014
// ---------------------------------------------------------------------
public interface CheckList extends ApplicationModule {
    List buscaChecklistsAuditoria(Long numPartySiteId);

    boolean verificaPrivilegioGestaoClientes(String userName);

    boolean verificaPrivilegioConsultarAlterarItensVerificacao(String userName);

    boolean verificaPossuiCodigoDefinitivo(String partySiteId);

    void salvar(List listaChecklistAud, String partySiteId);
}

