package br.com.br.gatend.GestaoCliente.v1.model.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 13 13:46:08 BRT 2014
// ---------------------------------------------------------------------
public interface LatitudeLongitudeAM extends ApplicationModule {
    void consultarLatitudeLongitude(Map parametros);


    void alteraValorSelecionadoPeloIndice(Map parametros);

    boolean confirmarLatitudeLongitude(Map parametros);

    void emptyTableLatLong();
}

