package br.com.br.gatend.GestaoCliente.v1.model.vo.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 17:29:00 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaChecklistVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ListaChecklistVORowClient() {
    }

    public oracle.jbo.domain.Number getChecChvChecklist() {
        return (oracle.jbo.domain.Number) getAttribute("ChecChvChecklist");
    }

    public void setChecChvChecklist(oracle.jbo.domain.Number value) {
        setAttribute("ChecChvChecklist", value);
    }

    public String getLookupCode() {
        return (String) getAttribute("LookupCode");
    }

    public String getChecIndVer() {
        return (String) getAttribute("ChecIndVer");
    }

    public String getMeaning() {
        return (String) getAttribute("Meaning");
    }

    public String getLastUpdateBy() {
        return (String) getAttribute("LastUpdateBy");
    }

    public String getChecTxtJus() {
        return (String) getAttribute("ChecTxtJus");
    }

    public String getUserName() {
        return (String) getAttribute("UserName");
    }

    public Date getLastUpdateDate() {
        return (Date) getAttribute("LastUpdateDate");
    }

    public oracle.jbo.domain.Number getPartySiteId() {
        return (oracle.jbo.domain.Number) getAttribute("PartySiteId");
    }

    public Boolean getChecked() {
        return (Boolean) getAttribute("Checked");
    }
}

