package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 16:54:42 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArLocationValuesVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ArLocationValuesVImpl() {
    }

    /**
     * Returns the variable value for sigla.
     * @return variable value for sigla
     */
    public String getsigla() {
        return (String) ensureVariableManager().getVariableValue("sigla");
    }

    /**
     * Sets <code>value</code> for variable sigla.
     * @param value value to bind as sigla
     */
    public void setsigla(String value) {
        ensureVariableManager().setVariableValue("sigla", value);
    }
}

