package br.com.br.gatend.GestaoCliente.v1.model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 16:54:42 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArLocationValuesVRowImpl extends ViewRowImpl {

    public static final int ENTITY_ARLOCATIONVALUESV = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreatedBy,
        CreationDate,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        LocationSegmentDescription,
        LocationSegmentId,
        LocationSegmentQualifier,
        LocationSegmentUserValue,
        LocationSegmentValue,
        LocationStructureId,
        RowId1,
        ParentSegmentId,
        SiglaPais,
        ArLocationValuesV1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LOCATIONSEGMENTDESCRIPTION = AttributesEnum.LocationSegmentDescription.index();
    public static final int LOCATIONSEGMENTID = AttributesEnum.LocationSegmentId.index();
    public static final int LOCATIONSEGMENTQUALIFIER = AttributesEnum.LocationSegmentQualifier.index();
    public static final int LOCATIONSEGMENTUSERVALUE = AttributesEnum.LocationSegmentUserValue.index();
    public static final int LOCATIONSEGMENTVALUE = AttributesEnum.LocationSegmentValue.index();
    public static final int LOCATIONSTRUCTUREID = AttributesEnum.LocationStructureId.index();
    public static final int ROWID1 = AttributesEnum.RowId1.index();
    public static final int PARENTSEGMENTID = AttributesEnum.ParentSegmentId.index();
    public static final int SIGLAPAIS = AttributesEnum.SiglaPais.index();
    public static final int ARLOCATIONVALUESV1 = AttributesEnum.ArLocationValuesV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ArLocationValuesVRowImpl() {
    }
}

