package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 03 15:46:17 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConsultaClientesVORowImpl extends ViewRowImpl {
    public static final int ENTITY_HZPARTYSITES = 0;
    public static final int ENTITY_HZ_CUST_ACCOUNTS = 1;
    public static final int ENTITY_HZCUSTACCTSITESALL = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RazaoSocial,
        NomeRazao2,
        TipoCliente,
        TipoClienteBasico,
        TipoClienteDigito,
        CodigoR3,
        PartySiteId,
        Status,
        StatusCliente,
        Aprovacao,
        GrupoContas,
        Logradouro,
        Endereco,
        Bairro,
        Pais,
        Cidade,
        Estado,
        Cep,
        Origem,
        Perfil,
        Principal,
        DataCriacao,
        Quadra,
        Lote,
        Complemento,
        Numero,
        PerfilVO2,
        PrincipalVo2,
        OrigemVo1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RAZAOSOCIAL = AttributesEnum.RazaoSocial.index();
    public static final int NOMERAZAO2 = AttributesEnum.NomeRazao2.index();
    public static final int TIPOCLIENTE = AttributesEnum.TipoCliente.index();
    public static final int TIPOCLIENTEBASICO = AttributesEnum.TipoClienteBasico.index();
    public static final int TIPOCLIENTEDIGITO = AttributesEnum.TipoClienteDigito.index();
    public static final int CODIGOR3 = AttributesEnum.CodigoR3.index();
    public static final int PARTYSITEID = AttributesEnum.PartySiteId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STATUSCLIENTE = AttributesEnum.StatusCliente.index();
    public static final int APROVACAO = AttributesEnum.Aprovacao.index();
    public static final int GRUPOCONTAS = AttributesEnum.GrupoContas.index();
    public static final int LOGRADOURO = AttributesEnum.Logradouro.index();
    public static final int ENDERECO = AttributesEnum.Endereco.index();
    public static final int BAIRRO = AttributesEnum.Bairro.index();
    public static final int PAIS = AttributesEnum.Pais.index();
    public static final int CIDADE = AttributesEnum.Cidade.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int CEP = AttributesEnum.Cep.index();
    public static final int ORIGEM = AttributesEnum.Origem.index();
    public static final int PERFIL = AttributesEnum.Perfil.index();
    public static final int PRINCIPAL = AttributesEnum.Principal.index();
    public static final int DATACRIACAO = AttributesEnum.DataCriacao.index();
    public static final int QUADRA = AttributesEnum.Quadra.index();
    public static final int LOTE = AttributesEnum.Lote.index();
    public static final int COMPLEMENTO = AttributesEnum.Complemento.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int PERFILVO2 = AttributesEnum.PerfilVO2.index();
    public static final int PRINCIPALVO2 = AttributesEnum.PrincipalVo2.index();
    public static final int ORIGEMVO1 = AttributesEnum.OrigemVo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ConsultaClientesVORowImpl() {
    }
}

