package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 03 15:46:19 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConsultaClientesVODefImpl extends ViewDefImpl {
    public ConsultaClientesVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public ConsultaClientesVODefImpl() {
    }
}

