package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 14:49:28 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndAttachedDocumentsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AttachedDocumentId,
        DocumentId,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        LastUpdateLogin,
        SeqNum,
        EntityName,
        Pk1Value,
        Pk2Value,
        Pk3Value,
        Pk4Value,
        Pk5Value,
        AutomaticallyAddedFlag,
        Column1,
        CategoryId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ATTACHEDDOCUMENTID = AttributesEnum.AttachedDocumentId.index();
    public static final int DOCUMENTID = AttributesEnum.DocumentId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int SEQNUM = AttributesEnum.SeqNum.index();
    public static final int ENTITYNAME = AttributesEnum.EntityName.index();
    public static final int PK1VALUE = AttributesEnum.Pk1Value.index();
    public static final int PK2VALUE = AttributesEnum.Pk2Value.index();
    public static final int PK3VALUE = AttributesEnum.Pk3Value.index();
    public static final int PK4VALUE = AttributesEnum.Pk4Value.index();
    public static final int PK5VALUE = AttributesEnum.Pk5Value.index();
    public static final int AUTOMATICALLYADDEDFLAG = AttributesEnum.AutomaticallyAddedFlag.index();
    public static final int COLUMN1 = AttributesEnum.Column1.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FndAttachedDocumentsVORowImpl() {
    }
}

