package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 14:49:29 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndAttachedDocumentsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FndAttachedDocumentsVOImpl() {
    }
}

