package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 14:31:19 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndDocumentsTLVODefImpl extends ViewDefImpl {
    public FndDocumentsTLVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public FndDocumentsTLVODefImpl() {
    }
}

