package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 16 15:23:37 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndLobsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FileId,
        FileName,
        FileContentType,
        FileData,
        UploadDate,
        ExpirationDate,
        ProgramName,
        ProgramTag,
        Language,
        OracleCharset,
        FileFormat;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FILEID = AttributesEnum.FileId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int FILECONTENTTYPE = AttributesEnum.FileContentType.index();
    public static final int FILEDATA = AttributesEnum.FileData.index();
    public static final int UPLOADDATE = AttributesEnum.UploadDate.index();
    public static final int EXPIRATIONDATE = AttributesEnum.ExpirationDate.index();
    public static final int PROGRAMNAME = AttributesEnum.ProgramName.index();
    public static final int PROGRAMTAG = AttributesEnum.ProgramTag.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int ORACLECHARSET = AttributesEnum.OracleCharset.index();
    public static final int FILEFORMAT = AttributesEnum.FileFormat.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FndLobsVORowImpl() {
    }
}

