package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 10 10:45:12 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndLookUpValuesVLU707GcPerfilClienteVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FndLookUpValuesVLU707GcPerfilClienteVVOImpl() {
    }
}

