package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 17 14:08:46 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FndUserVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FndUserVOImpl() {
    }

    /**
     * Returns the variable value for numUserId.
     * @return variable value for numUserId
     */
    public Long getnumUserId() {
        return (Long) ensureVariableManager().getVariableValue("numUserId");
    }

    /**
     * Sets <code>value</code> for variable numUserId.
     * @param value value to bind as numUserId
     */
    public void setnumUserId(Long value) {
        ensureVariableManager().setVariableValue("numUserId", value);
    }

    /**
     * Returns the variable value for txtUserName.
     * @return variable value for txtUserName
     */
    public String gettxtUserName() {
        return (String) ensureVariableManager().getVariableValue("txtUserName");
    }

    /**
     * Sets <code>value</code> for variable txtUserName.
     * @param value value to bind as txtUserName
     */
    public void settxtUserName(String value) {
        ensureVariableManager().setVariableValue("txtUserName", value);
    }
}

