package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 25 10:17:29 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HzCodDefinitivoSAPVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HzCodDefinitivoSAPVOImpl() {
    }

    /**
     * Returns the variable value for numPartySiteId.
     * @return variable value for numPartySiteId
     */
    public Long getnumPartySiteId() {
        return (Long) ensureVariableManager().getVariableValue("numPartySiteId");
    }

    /**
     * Sets <code>value</code> for variable numPartySiteId.
     * @param value value to bind as numPartySiteId
     */
    public void setnumPartySiteId(Long value) {
        ensureVariableManager().setVariableValue("numPartySiteId", value);
    }
}

