package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 17:37:53 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HzPartiesU707GcClienteVVORowImpl extends ViewRowImpl {
    public static final int ENTITY_HZPARTIES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PartyId,
        PartyName,
        Rowid;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PARTYID = AttributesEnum.PartyId.index();
    public static final int PARTYNAME = AttributesEnum.PartyName.index();
    public static final int ROWID = AttributesEnum.Rowid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HzPartiesU707GcClienteVVORowImpl() {
    }
}

