package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 21 11:24:19 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaAnexosVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ListaAnexosVOImpl() {
    }
}

