package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 21 11:24:19 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaAnexosVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Sequencial,
        Categoria,
        Descricao,
        NomeArquivo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SEQUENCIAL = AttributesEnum.Sequencial.index();
    public static final int CATEGORIA = AttributesEnum.Categoria.index();
    public static final int DESCRICAO = AttributesEnum.Descricao.index();
    public static final int NOMEARQUIVO = AttributesEnum.NomeArquivo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ListaAnexosVORowImpl() {
    }
}

