package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 10 14:19:40 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U536BrRolesMenuVVODefImpl extends ViewDefImpl {
    public U536BrRolesMenuVVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public U536BrRolesMenuVVODefImpl() {
    }
}

