package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 18 15:54:24 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U536HzCheckListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public U536HzCheckListVOImpl() {
    }

    /**
     * Returns the variable value for numPartySiteId.
     * @return variable value for numPartySiteId
     */
    public Long getnumPartySiteId() {
        return (Long) ensureVariableManager().getVariableValue("numPartySiteId");
    }

    /**
     * Sets <code>value</code> for variable numPartySiteId.
     * @param value value to bind as numPartySiteId
     */
    public void setnumPartySiteId(Long value) {
        ensureVariableManager().setVariableValue("numPartySiteId", value);
    }

    /**
     * Returns the variable value for txtCodItemAud.
     * @return variable value for txtCodItemAud
     */
    public String gettxtCodItemAud() {
        return (String) ensureVariableManager().getVariableValue("txtCodItemAud");
    }

    /**
     * Sets <code>value</code> for variable txtCodItemAud.
     * @param value value to bind as txtCodItemAud
     */
    public void settxtCodItemAud(String value) {
        ensureVariableManager().setVariableValue("txtCodItemAud", value);
    }

    /**
     * Returns the variable value for numChvChecklist.
     * @return variable value for numChvChecklist
     */
    public Long getnumChvChecklist() {
        return (Long) ensureVariableManager().getVariableValue("numChvChecklist");
    }

    /**
     * Sets <code>value</code> for variable numChvChecklist.
     * @param value value to bind as numChvChecklist
     */
    public void setnumChvChecklist(Long value) {
        ensureVariableManager().setVariableValue("numChvChecklist", value);
    }
}

