package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 10 14:19:40 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U536BrRolesMenuVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public U536BrRolesMenuVVOImpl() {
    }


    /**
     * Returns the variable value for txtUserName.
     * @return variable value for txtUserName
     */
    public String gettxtUserName() {
        return (String) ensureVariableManager().getVariableValue("txtUserName");
    }

    /**
     * Sets <code>value</code> for variable txtUserName.
     * @param value value to bind as txtUserName
     */
    public void settxtUserName(String value) {
        ensureVariableManager().setVariableValue("txtUserName", value);
    }

    /**
     * Returns the variable value for chaveUsuario.
     * @return variable value for chaveUsuario
     */
    public String getchaveUsuario() {
        return (String) ensureVariableManager().getVariableValue("chaveUsuario");
    }

    /**
     * Sets <code>value</code> for variable chaveUsuario.
     * @param value value to bind as chaveUsuario
     */
    public void setchaveUsuario(String value) {
        ensureVariableManager().setVariableValue("chaveUsuario", value);
    }
}

