package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 18 16:18:24 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U707GcAnexoVVORowImpl extends ViewRowImpl {
    public static final int ENTITY_U707GCANEXOVEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AttachedDocumentId,
        AutomaticallyAddedFlag,
        CategoryDescription,
        CategoryId,
        Column1,
        CreatedBy,
        CreationDate,
        DatatypeId,
        DatatypeName,
        DocumentDescription,
        DocumentId,
        EndDateActive,
        EntityName,
        FileName,
        ImageType,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        MediaId,
        Pk1Value,
        Pk2Value,
        Pk3Value,
        Pk4Value,
        Pk5Value,
        PublishFlag,
        SecurityId,
        SecurityType,
        SeqNum,
        StartDateActive,
        UsageType,
        UserEntityName,
        UserEntityPrompt;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return U707GcAnexoVVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return U707GcAnexoVVORowImpl.AttributesEnum.firstIndex() +
                   U707GcAnexoVVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = U707GcAnexoVVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ATTACHEDDOCUMENTID = AttributesEnum.AttachedDocumentId.index();
    public static final int AUTOMATICALLYADDEDFLAG = AttributesEnum.AutomaticallyAddedFlag.index();
    public static final int CATEGORYDESCRIPTION = AttributesEnum.CategoryDescription.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int COLUMN1 = AttributesEnum.Column1.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DATATYPEID = AttributesEnum.DatatypeId.index();
    public static final int DATATYPENAME = AttributesEnum.DatatypeName.index();
    public static final int DOCUMENTDESCRIPTION = AttributesEnum.DocumentDescription.index();
    public static final int DOCUMENTID = AttributesEnum.DocumentId.index();
    public static final int ENDDATEACTIVE = AttributesEnum.EndDateActive.index();
    public static final int ENTITYNAME = AttributesEnum.EntityName.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int IMAGETYPE = AttributesEnum.ImageType.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int MEDIAID = AttributesEnum.MediaId.index();
    public static final int PK1VALUE = AttributesEnum.Pk1Value.index();
    public static final int PK2VALUE = AttributesEnum.Pk2Value.index();
    public static final int PK3VALUE = AttributesEnum.Pk3Value.index();
    public static final int PK4VALUE = AttributesEnum.Pk4Value.index();
    public static final int PK5VALUE = AttributesEnum.Pk5Value.index();
    public static final int PUBLISHFLAG = AttributesEnum.PublishFlag.index();
    public static final int SECURITYID = AttributesEnum.SecurityId.index();
    public static final int SECURITYTYPE = AttributesEnum.SecurityType.index();
    public static final int SEQNUM = AttributesEnum.SeqNum.index();
    public static final int STARTDATEACTIVE = AttributesEnum.StartDateActive.index();
    public static final int USAGETYPE = AttributesEnum.UsageType.index();
    public static final int USERENTITYNAME = AttributesEnum.UserEntityName.index();
    public static final int USERENTITYPROMPT = AttributesEnum.UserEntityPrompt.index();

    /**
     * This is the default constructor (do not remove).
     */
    public U707GcAnexoVVORowImpl() {
    }
}

