package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 14:40:03 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U707GcCategAnexoVVORowImpl extends ViewRowImpl {
    public static final int ENTITY_U707GCCATEGANEXOVEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Categoria,
        CategoryId,
        FunctionName,
        FunctionType;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CATEGORIA = AttributesEnum.Categoria.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int FUNCTIONNAME = AttributesEnum.FunctionName.index();
    public static final int FUNCTIONTYPE = AttributesEnum.FunctionType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public U707GcCategAnexoVVORowImpl() {
    }
}

