package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 14:40:04 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U707GcCategAnexoVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public U707GcCategAnexoVVOImpl() {
    }
}

