package br.com.br.gatend.GestaoCliente.v1.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 18 16:18:25 BRT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class U707GcAnexoVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public U707GcAnexoVVOImpl() {
    }

    /**
     * Returns the variable value for codigoCliente.
     * @return variable value for codigoCliente
     */
    public String getcodigoCliente() {
        return (String) ensureVariableManager().getVariableValue("codigoCliente");
    }

    /**
     * Sets <code>value</code> for variable codigoCliente.
     * @param value value to bind as codigoCliente
     */
    public void setcodigoCliente(String value) {
        ensureVariableManager().setVariableValue("codigoCliente", value);
    }
}

